### ISSUE TITLE
Dark background

### ISSUE THREAD

**Issue by houdinii** [4silvertooth/QwikTape#1]
I prefer darkmode and it looks like the background is implemented, outside of:

`<Color (editor-paper)>Paper</Color>`

being included in settings.js around line 54. I wasn't sure if this was unintentional, but it appears to work well on Windows. Great tool by the way!

**Comment by 4silvertooth** [comment]
Yes I've not included that in settings, but yes will update prefence for paper color and lined vs blank paper.

**Comment by 4silvertooth** [comment]
> I prefer darkmode and it looks like the background is implemented, outside of:
> 
> `<Color (editor-paper)>Paper</Color>`
> 
> being included in settings.js around line 54. I wasn't sure if this was unintentional, but it appears to work well on Windows. Great tool by the way!

Are you talking about the paper color or the backdrop of paper? what did you meant by background?

**Comment by houdinii** [comment]
I personally just changed the editor-paper color, which kept the lines visible, and it worked for me.  It still had grey for the window, borders, and scroll bar.

**Comment by 4silvertooth** [comment]
Ya I had not included that as the label "Paper" was not readable with same background for it, but now I've made few changes so that it's readable and will be up in next update.

**Comment by houdinii** [comment]
I'll be looking forward to it. It's already found a permanent spot on my ultrawide monitor.
