### ISSUE TITLE
Cool idea. Dies a horrible death under Wayland

### ISSUE THREAD

**Issue by mlongval** [4silvertooth/QwikTape#2]
Cloned the repository and chmod +x run-linux.sh, then ran it....

```
(scapp:3787030): Gdk-CRITICAL **: 14:47:43.381: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed
root [object Object]
tape [object Object]
tape [object Object]

(scapp:3787030): Gdk-WARNING **: 14:47:44.781: ../../../../../gdk/x11/gdkwindow-x11.c:5653 drawable is not a native X11 window
Segmentation fault (core dumped)
```

Running on Ubuntu 22.04 Gnome on Wayland

**Comment by 4silvertooth** [comment]
That was a known bug in Sciter sdk, I've updated the sdk to latest now, can you try again? I don't have access to Linux box right now to test it.

**Comment by mlongval** [comment]
Ok. Redownloaded. Did the chmod +x thing. Now it runs. I can add text, move up and down, add lines, but if I add an operation OTHER than +, ie (*) x or / (division) it segfaults.

`
./run-linux.sh: line 5: 19820 Segmentation fault      (core dumped) sdk/bin/linux/x64/scapp src/main.htm
`
Is there some logfile I could send you?

**Comment by 4silvertooth** [comment]
There are no logs as such, mult and div to replace the symbol uses plaintext transaction which had a bug-fix in SDK recently, I'll see into any regression bug.

@mlongval can you check if it segfaults if you turn off mult and div symbol replacement in seetings (click the gear icon)

**Comment by 4silvertooth** [comment]
@mlongval 
This [commit](https://github.com/4silvertooth/QwikTape/commit/d266500e9a130e675d75f54f725c7c7961cf0a35) should fix the division and multiplication symbol replacement crash.
