### ISSUE TITLE
cmd line option "path to qwiktapes.db"

### ISSUE THREAD

**Issue by lintalist** [4silvertooth/QwikTape#3]
On Windows it saves "qwiktapes.db" in the user's documents folder, to make it portable (flash drive, cloud drive) an option to pass on the (relative) path to qwiktapes.db would be useful.

`qwiktape.exe f:\path-to\qwiktapes.db`

**Comment by 4silvertooth** [comment]
If you move the `qwiktapes.db` file from `Documents` to where executable resides, it will open that file from next version.

**Comment by lintalist** [comment]
Sounds good!
