### ISSUE TITLE
Assumes a `document` path that in Linux fails

### ISSUE THREAD

**Issue by yujikiriki** [4silvertooth/QwikTape#4]
[This](https://github.com/4silvertooth/QwikTape/blob/966ecd02d360fb58e69a95d18ab9f4d8840cd3e7/src/storage/storage.js#L8) line assumes that there is going to be a `document` path set.

It fails in Arch Linux.

**Comment by 4silvertooth** [comment]
If `document` path is not available, it will create the tapes file besides the executable.
