### ISSUE TITLE
Enhancement - Focus tape first

### ISSUE THREAD

**Issue by jobytoss** [4silvertooth/QwikTape#6]
Hello!
Would be nice to have the focus on the current tape when opening the app, so one can start typing calculations immediately upon opening. As it stand now (v.0.4), I have to hit TAB key 5 times or focus the tape with a mouse click.
Thank you for the portable version and for implementing the ability to use the ESC key!

**Comment by 4silvertooth** [comment]
On opening app it should focus tape. In 0.4 I've made changes to set caret to last position too.

**Comment by jobytoss** [comment]
Somehow when I start the app with an empty "My tape - 2" for example, the tape is not in focus. I'll keep tweaking it, maybe it's something on my end (I'm on Win 10 x64 with latest updates).

**Comment by 4silvertooth** [comment]
I guess there is a bug in sciter SDK, I'll have to check, I had a workaround for it, but I'll have to raise issue with sciter SDK.
