### ISSUE TITLE
pdf export not work, and no error

### ISSUE THREAD

**Issue by badiku** [4silvertooth/QwikTape#8]
no pdf is generated, and no error reported.

if in debug mode, it says that PDF is null

```
function toPdf(val, fileName){    
    console.log('PDF type = object ? ', typeof PDF === 'object');
    console.log('PDF == null ? ',  PDF === null);
    ...
    PDF.newDoc();
    ...}
```    

> PDF type = object ? true
> PDF == null ? true
> TypeError: cannot read property 'newDoc' of null
>     at toPdf pdf.js   

using qwiktape-v0.6-windows-portable.zip  on win10 19044

**Comment by 4silvertooth** [comment]
Please use the sciter-pdf.dll from here as of now. https://github.com/4silvertooth/sciter-pdf/releases
